### ISSUE TITLE
only last band contributes

### ISSUE THREAD

**Issue by NPounder** [multiply-org/KaFKA-InferenceEngine#8]
As far as I can see the bands aren't being combined at all:

https://github.com/multiply-org/KaFKA-InferenceEngine/blob/659ec416889ff70b5446b499c9f11f1377e1f504/kafka/linear_kf.py#L205-L208

The output from the last band overwrites the previous bands.

How are they intended to be combined?

**Comment by jgomezdans** [comment]
Bummer, wrong bug referred to. I think this is solved with 12af15c8aa1fc028c21e5dae2d0c1e82a5d99e3a

Can you test?

**Comment by NPounder** [comment]
I've submitted a pull request #9 with a minor fix.  This now runs and produces output but LAI is dampened (reduced phenology) compared to what we were producing a couple of months ago. I'll put a new issue with some plots for that though.

**Comment by jgomezdans** [comment]
Is the retrieved lai spatially smooth? What about the other parameters?

**Comment by NPounder** [comment]
I'll put some images up in a minute in a new issue. I've just run it on a 10 by 10 chip so it's hard to judge the smoothness well but I think it is smooth. The features are the same shape as those from a couple of months ago its just that there is little dynamic range in LAI anymore. I've only looked at a single time-step for the other parameters - there is not much going on. I'll plot more.

**Comment by NPounder** [comment]
I remember we did change one of the parameters in the prior a little while back but I can't find what it was before - that might be causing the dampening...
